# Generated by Django 5.2.11 on 2026-03-17 15:39

import core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamSettings',
            fields=[
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='exam_settings', serialize=False, to='organizations.organizations')),
                ('include_active_students', models.BooleanField(default=True, help_text='Faol talabalarni hisobga olish')),
                ('include_trial_students', models.BooleanField(default=False, help_text='Sinov darsidagi talabalarni hisobga olish')),
                ('include_archived_students', models.BooleanField(default=False, help_text='Arxivlangan talabalarni hisobga olish')),
                ('include_frozen_students', models.BooleanField(default=False, help_text='Muzlatilgan talabalarni hisobga olish')),
                ('include_deleted_students', models.BooleanField(default=False, help_text="O'chirilgan talabalarni hisobga olish")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Exam Setting',
                'verbose_name_plural': 'Exam Settings',
                'db_table': 'exam_settings',
            },
        ),
        migrations.CreateModel(
            name='OrganizationSettings',
            fields=[
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='settings', serialize=False, to='organizations.organizations')),
                ('payment_mode', models.CharField(choices=[('monthly', 'Oylik (kalendar oyiga)'), ('per_lesson', 'Darslik'), ('package', 'Paket')], default='monthly', max_length=20)),
                ('exclude_trial_students', models.BooleanField(default=True, help_text='Sinov darsidagi talabalarni hisobga olmang')),
                ('exclude_archived_students', models.BooleanField(default=True, help_text='Arxivlangan talabalarni hisobga olmang')),
                ('include_student_discount', models.BooleanField(default=False, help_text='Talaba chegirmasini hisobga oling')),
                ('apply_discount_to_salary', models.BooleanField(default=False, help_text="O'qituvchining maoshida o'quvchi chegirmasini hisobga oling")),
                ('calculate_archived_salary', models.BooleanField(default=False, help_text="Arxivlangan o'quvchilarga maosh hisoblang")),
                ('link_salary_to_attendance', models.BooleanField(default=True, help_text="O'qituvchining maoshini davomatga ulang")),
                ('only_main_teacher_attendance', models.BooleanField(default=False, help_text='Faqatgina guruh ustozi belgilagan davomatlarga maosh hisoblash')),
                ('only_attended_lessons', models.BooleanField(default=True, help_text="Faqatgina o'quvchi kelgan darslarga maosh hisoblash")),
                ('calculate_trial_salary', models.BooleanField(default=False, help_text="Sinov darsi holatidagi o'quvchilar uchun maosh hisoblash")),
                ('include_frozen_students', models.BooleanField(default=False, help_text="Muzlatilgan o'quvchilarni hisobga olish")),
                ('allow_teacher_sms', models.BooleanField(default=False, help_text="O'qituvchilarga SMS yuborishga ruxsat bering")),
                ('hide_student_data_from_teacher', models.BooleanField(default=False, help_text="O'qituvchilarga talabalar ma'lumotlarini yashirish")),
                ('attendance_only_during_lesson', models.BooleanField(default=False, help_text='Davomatni faqat dars davomida belgilash')),
                ('allow_schedule_overlap', models.BooleanField(default=False, help_text="Jadval: guruhlarni bitta kabinet/o'qituvchi bilan kesib o'tishga ruxsat")),
                ('show_group_balance', models.BooleanField(default=True, help_text="Guruh balansini ko'rsatish")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Organization Setting',
                'verbose_name_plural': 'Organization Settings',
                'db_table': 'organization_settings',
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('description', models.TextField(blank=True, help_text='Qo‘shimcha ma’lumot', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Section',
                'verbose_name_plural': 'Sections',
                'db_table': 'sections',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LandingPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Landing sahifa nomi', max_length=250)),
                ('slug', models.SlugField(help_text='URL qismi', max_length=250, unique=True)),
                ('source', models.CharField(choices=[('telegram', 'Telegram'), ('instagram', 'Instagram'), ('facebook', 'Facebook'), ('website', 'Website'), ('offline', 'Offline'), ('youtube', 'YouTube'), ('tiktok', 'TikTok'), ('other', 'Boshqa')], help_text='Qaysi platformadan', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='Faolmi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(help_text='Qaysi filialga biriktiriladi', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='landing_branch', to='organizations.branch')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='landing_pages', to='organizations.organizations')),
                ('section', models.ForeignKey(blank=True, help_text="Qaysi kurs/yo'nalish", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='landing_section', to='organizations.section')),
            ],
            options={
                'verbose_name': 'Landing Page',
                'verbose_name_plural': 'Landing Pages',
                'db_table': 'landing_pages',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LandingPageSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(help_text="To'liq ismi", max_length=250)),
                ('phone', models.CharField(help_text='Telefon raqam', max_length=20, validators=[core.validators.uz_phone_validator])),
                ('comment', models.TextField(blank=True, help_text="Qo'shimcha izoh", null=True)),
                ('source', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submission_branch', to='organizations.branch')),
                ('landing_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='organizations.landingpage')),
            ],
            options={
                'verbose_name': 'Landing Page Submission',
                'verbose_name_plural': 'Landing Page Submissions',
                'db_table': 'landing_page_submissions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=100)),
                ('object_type', models.CharField(choices=[('student', 'Student'), ('group', 'Group'), ('lead', 'Lead')], max_length=20)),
                ('branch_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_%(class)ss', to='organizations.branch')),
                ('organization_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='organizations.organizations')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
