# Generated by Django 4.2.7 on 2025-12-27 09:22

import core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmsTemplates',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=250)),
                ('text', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('branch_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_%(class)ss', to='organizations.branch')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='templates_created', to='accounts.employee')),
                ('organization_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='organizations.organizations')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SmsSchedules',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=250)),
                ('target_type', models.CharField(choices=[('lead', 'Lead'), ('student', 'Student'), ('group', 'Group'), ('debtors', 'Debtors')], max_length=20)),
                ('target_id', models.UUIDField()),
                ('send_at', models.DateTimeField(blank=True, help_text='Bir martalik yuborish vaqti', null=True)),
                ('cron_expression', models.CharField(blank=True, help_text='Takroriy SMS uchun cron ifoda', max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('branch_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_%(class)ss', to='organizations.branch')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedules_created', to='accounts.employee')),
                ('organization_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='organizations.organizations')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template', to='communication.smstemplates')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SMSMessages',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipent_type', models.CharField(choices=[('lead', 'Lead'), ('student', 'Student'), ('group', 'Group'), ('debtors', 'Debtors'), ('employee', 'Employee')], max_length=20)),
                ('recipent_id', models.UUIDField()),
                ('phone', models.CharField(max_length=20, validators=[core.validators.uz_phone_validator])),
                ('text', models.TextField()),
                ('send_type', models.CharField(choices=[('manual', 'Manual'), ('auto', 'Auto')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed')], max_length=20)),
                ('sent_at', models.DateTimeField()),
                ('branch_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_%(class)ss', to='organizations.branch')),
                ('organization_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='organizations.organizations')),
                ('schedule', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedule', to='communication.smsschedules')),
                ('template', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='SMS_template', to='communication.smstemplates')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
