# Generated by Django 5.2.11 on 2026-03-17 15:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('communication', '0001_initial'),
        ('organizations', '0002_examsettings_organizationsettings_section_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmsProvider',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('provider', models.CharField(choices=[('playmobile', 'PlayMobile'), ('eskiz', 'Eskiz')], max_length=20, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=255)),
                ('nickname', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('balance', models.DecimalField(decimal_places=2, default=0, help_text='SMS balans', max_digits=10)),
                ('branch_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_%(class)ss', to='organizations.branch')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='providers_created', to='accounts.employee')),
                ('organization_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='organizations.organizations')),
            ],
            options={
                'verbose_name': 'SMS Provider',
                'verbose_name_plural': 'SMS Providers',
                'db_table': 'sms_provider',
            },
        ),
    ]
