# Generated by Django 4.2.7 on 2025-12-27 09:22

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('entity_type', models.CharField(choices=[('lead', 'Lead'), ('student', 'Student'), ('payment', 'Payment'), ('group', 'Group'), ('user', 'User'), ('other', 'Other')], max_length=30)),
                ('entity_id', models.UUIDField(help_text="O'zgartilgan entity UUID si")),
                ('action', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete')], max_length=20)),
                ('old_data', models.JSONField(blank=True, null=True)),
                ('new_action', models.JSONField(blank=True, null=True)),
                ('performed_by_role', models.CharField(max_length=50)),
                ('branch_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_%(class)ss', to='organizations.branch')),
                ('organization_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='organizations.organizations')),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performed_by', to='accounts.employee')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
