# Generated by Django 4.2.7 on 2025-12-27 09:22

import core.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CRMLead',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('full_name', models.CharField(max_length=250)),
                ('phone_number', models.CharField(max_length=20, unique=True, validators=[core.validators.uz_phone_validator])),
                ('gender', models.CharField(blank=True, choices=[('M', 'Erkak'), ('F', 'Ayol')], max_length=1, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('converted', 'Converted'), ('lost', 'Lost')], default='active', max_length=15)),
                ('expected_course', models.CharField(blank=True, max_length=150)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('converted_student_id', models.PositiveIntegerField()),
                ('assigned_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_to', to=settings.AUTH_USER_MODEL)),
                ('branch_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_%(class)ss', to='organizations.branch')),
                ('organization_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='organizations.organizations')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CRMSource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=250)),
                ('branch_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_%(class)ss', to='organizations.branch')),
                ('organization_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='organizations.organizations')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CRMPipelines',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=250)),
                ('position', models.PositiveIntegerField()),
                ('branch_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_%(class)ss', to='organizations.branch')),
                ('organization_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='organizations.organizations')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CRMLostReason',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=200)),
                ('branch_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_%(class)ss', to='organizations.branch')),
                ('organization_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='organizations.organizations')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CRMLeadsHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('branch_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_%(class)ss', to='organizations.branch')),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lead', to='crm.crmlead')),
                ('new_pipeline', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='crm.crmpipelines')),
                ('old_pipeline', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='crm.crmpipelines')),
                ('organization_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='organizations.organizations')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CRMLeadNotes',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.TextField()),
                ('branch_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_%(class)ss', to='organizations.branch')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='crm.crmlead')),
                ('organization_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='organizations.organizations')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='note_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CRMLeadLost',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('comment', models.TextField(blank=True)),
                ('branch_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_%(class)ss', to='organizations.branch')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='crm.crmlead')),
                ('organization_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='organizations.organizations')),
                ('reason', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET, related_name='reason', to='crm.crmlostreason')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='crmlead',
            name='pipline',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pipline', to='crm.crmpipelines'),
        ),
        migrations.AddField(
            model_name='crmlead',
            name='source',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source', to='crm.crmsource'),
        ),
        migrations.CreateModel(
            name='CRMActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activity_type', models.CharField(choices=[('call', 'Call'), ('sms', 'SMS'), ('meeting', 'Meeting')], max_length=10)),
                ('result', models.CharField(blank=True, max_length=250)),
                ('branch_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_%(class)ss', to='organizations.branch')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_by', to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='crm.crmlead')),
                ('organization_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='organizations.organizations')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
