# Generated by Django 6.0.1 on 2026-01-07 11:30

import core.models
import core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=250)),
                ('code', models.CharField(blank=True, max_length=200)),
                ('monthly_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('lesson_month', models.PositiveIntegerField()),
                ('comment', models.TextField(blank=True)),
                ('branch_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_%(class)ss', to='organizations.branch')),
                ('organization_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='organizations.organizations')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=250)),
                ('status', models.CharField(choices=[('active', 'Active'), ('expried', 'Expired'), ('archived', 'Archived')], default='active', max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('branch_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_%(class)ss', to='organizations.branch')),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group_course', to='academics.course')),
                ('organization_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='organizations.organizations')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Exams',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=250)),
                ('exam_date', models.DateField()),
                ('min_score', models.DecimalField(decimal_places=2, max_digits=12)),
                ('max_score', models.DecimalField(decimal_places=2, max_digits=12)),
                ('description', models.TextField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to=core.models.exam_files_upload_path)),
                ('branch_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_%(class)ss', to='organizations.branch')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exam_created', to='accounts.employee')),
                ('organization_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='organizations.organizations')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams_group', to='academics.group')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GroupTeacher',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('branch_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_%(class)ss', to='organizations.branch')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group', to='academics.group')),
                ('organization_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='organizations.organizations')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher', to='accounts.employee')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LeaveReason',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=250)),
                ('is_active', models.BooleanField(default=True)),
                ('branch_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_%(class)ss', to='organizations.branch')),
                ('organization_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='organizations.organizations')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LessonSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('day_type', models.CharField(choices=[('odd', 'Odd days'), ('even', 'Even days'), ('every', 'EveryDaye')], max_length=20)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('branch_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_%(class)ss', to='organizations.branch')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_group', to='academics.group')),
                ('organization_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='organizations.organizations')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LessonTime',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=250)),
                ('code', models.CharField(blank=True, max_length=200)),
                ('branch_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_%(class)ss', to='organizations.branch')),
                ('organization_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='organizations.organizations')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='course',
            name='lesson',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Course_lesson', to='academics.lessontime'),
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=250)),
                ('capacity', models.PositiveIntegerField()),
                ('branch_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_%(class)ss', to='organizations.branch')),
                ('organization_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='organizations.organizations')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='group',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group_room', to='academics.room'),
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('full_name', models.CharField(max_length=250)),
                ('photo', models.ImageField(blank=True, null=True, upload_to=core.models.student_avatar_upload_path)),
                ('phone_number', models.CharField(max_length=20, unique=True, validators=[core.validators.uz_phone_validator])),
                ('phone_number2', models.CharField(max_length=20, unique=True, validators=[core.validators.uz_phone_validator])),
                ('password', models.CharField(blank=True, max_length=10, null=True)),
                ('parent_name', models.CharField(blank=True, max_length=20, null=True)),
                ('parent_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.CharField(blank=True, max_length=20, null=True)),
                ('telegram_username', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.TextField()),
                ('branch_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_%(class)ss', to='organizations.branch')),
                ('organization_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='organizations.organizations')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ExamResults',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('score', models.DecimalField(decimal_places=2, max_digits=12)),
                ('comment', models.TextField(blank=True, null=True)),
                ('branch_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_%(class)ss', to='organizations.branch')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exam_res_created', to='accounts.employee')),
                ('organization_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='organizations.organizations')),
                ('exam', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exam', to='academics.exams')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exam_res_student', to='academics.student')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StudentBalanceHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('applied_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('discount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('branch_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_%(class)ss', to='organizations.branch')),
                ('organization_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='organizations.organizations')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='SBHistory_student', to='academics.student')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StudentBalances',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('branch_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_%(class)ss', to='organizations.branch')),
                ('organization_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='organizations.organizations')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Sbalances_student', to='academics.student')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StudentFreezes',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('freeze_start_date', models.DateField()),
                ('freeze_end_date', models.DateField()),
                ('reason', models.TextField()),
                ('recalc_balance', models.BooleanField(default=False)),
                ('branch_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_%(class)ss', to='organizations.branch')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='SFreeze_created', to='accounts.employee')),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='SFreeze_group', to='academics.group')),
                ('organization_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='organizations.organizations')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='SFreeze_student', to='academics.student')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StudentGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('joined_at', models.DateField()),
                ('left_at', models.DateField()),
                ('end_date', models.DateField()),
                ('branch_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_%(class)ss', to='organizations.branch')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Sgroup_group', to='academics.group')),
                ('organization_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='organizations.organizations')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Sgroup_student', to='academics.student')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Attendence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lesson_date', models.DateField()),
                ('is_present', models.BooleanField(default=False)),
                ('branch_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_%(class)ss', to='organizations.branch')),
                ('marked_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='A_marked', to='accounts.employee')),
                ('organization_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='organizations.organizations')),
                ('student_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='A_Sgroup', to='academics.studentgroup')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StudentGroupLeaves',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('leave_date', models.DateTimeField()),
                ('comment', models.TextField(blank=True, null=True)),
                ('recalc_balance', models.BooleanField(default=False)),
                ('refound_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('branch_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_%(class)ss', to='organizations.branch')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='SGLeave_created', to='accounts.employee')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='SGLeave_group', to='academics.group')),
                ('leave_reason', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='SGLeave_Lreason', to='academics.leavereason')),
                ('organization_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='organizations.organizations')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='SGLeave_student', to='academics.student')),
                ('student_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='SGLeave_Sgroup', to='academics.studentgroup')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StudentPricing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('price_override', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reason', models.TextField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('branch_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_%(class)ss', to='organizations.branch')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Spricing_course', to='academics.course')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Sprice_created', to='accounts.employee')),
                ('organization_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='organizations.organizations')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Spricing_student', to='academics.student')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StudentTarnsactions',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('transaction_type', models.CharField(choices=[('payment', "To'lov"), ('refund', 'Pul qaytarish'), ('discount', 'Chegirma'), ('correction', 'Tuzatish')], max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_type', models.CharField(choices=[('cash', 'Naqd'), ('card', 'Karta'), ('transfer', "O'tkazma")], max_length=30)),
                ('transaction_date', models.DateTimeField()),
                ('comment', models.TextField()),
                ('accepted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Strans_accepted', to='accounts.employee')),
                ('branch_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_%(class)ss', to='organizations.branch')),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Strans_group', to='academics.group')),
                ('organization_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='organizations.organizations')),
                ('related_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='academics.studenttarnsactions')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Strans_student', to='academics.student')),
                ('student_group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Strans_Sgroup', to='academics.studentgroup')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TeacherSalaryCalculations',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('month', models.CharField(max_length=250)),
                ('student_count', models.PositiveIntegerField()),
                ('percent', models.DecimalField(decimal_places=2, max_digits=6)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('calculated_at', models.DateField()),
                ('branch_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_%(class)ss', to='organizations.branch')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='TSalCal_group', to='academics.group')),
                ('organization_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='organizations.organizations')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='TSalCal_teacher', to='accounts.employee')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TeacherSalaryPayments',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_date', models.DateField()),
                ('payment_type', models.CharField(choices=[('cash', 'Naqt Pul'), ('card', 'Plastik karta'), ('check', "Bankdan o'tkazma")], max_length=20)),
                ('branch_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_%(class)ss', to='organizations.branch')),
                ('organization_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='organizations.organizations')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='TSalPay_teacher', to='accounts.employee')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TeacherSalaryRules',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('percent_per_student', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fixed_bonus', models.DecimalField(decimal_places=2, max_digits=12)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField()),
                ('branch_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_%(class)ss', to='organizations.branch')),
                ('organization_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='organizations.organizations')),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='TSalRul_teacher', to='accounts.employee')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
