# Generated by Django 4.2.7 on 2025-12-27 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('organizations', '0001_initial'),
        ('academics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachersalaryrules',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='TSalRul_teacher', to='accounts.employee'),
        ),
        migrations.AddField(
            model_name='teachersalarypayments',
            name='branch_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_%(class)ss', to='organizations.branch'),
        ),
        migrations.AddField(
            model_name='teachersalarypayments',
            name='organization_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='organizations.organizations'),
        ),
        migrations.AddField(
            model_name='teachersalarypayments',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='TSalPay_teacher', to='accounts.employee'),
        ),
        migrations.AddField(
            model_name='teachersalarycalculations',
            name='branch_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_%(class)ss', to='organizations.branch'),
        ),
        migrations.AddField(
            model_name='teachersalarycalculations',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='TSalCal_group', to='academics.group'),
        ),
        migrations.AddField(
            model_name='teachersalarycalculations',
            name='organization_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='organizations.organizations'),
        ),
        migrations.AddField(
            model_name='teachersalarycalculations',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='TSalCal_teacher', to='accounts.employee'),
        ),
        migrations.AddField(
            model_name='taskpermissions',
            name='branch_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_%(class)ss', to='organizations.branch'),
        ),
        migrations.AddField(
            model_name='taskpermissions',
            name='organization_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='organizations.organizations'),
        ),
        migrations.AddField(
            model_name='taskpermissions',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='TPerm_task', to='academics.task'),
        ),
        migrations.AddField(
            model_name='taskpermissions',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='TPerm_user', to='accounts.employee'),
        ),
        migrations.AddField(
            model_name='tasknotifications',
            name='branch_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_%(class)ss', to='organizations.branch'),
        ),
        migrations.AddField(
            model_name='tasknotifications',
            name='organization_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='organizations.organizations'),
        ),
        migrations.AddField(
            model_name='tasknotifications',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='TNotifi_task', to='academics.task'),
        ),
        migrations.AddField(
            model_name='tasknotifications',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='TNotifi_user', to='accounts.employee'),
        ),
        migrations.AddField(
            model_name='taskcomments',
            name='branch_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_%(class)ss', to='organizations.branch'),
        ),
        migrations.AddField(
            model_name='taskcomments',
            name='organization_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='organizations.organizations'),
        ),
        migrations.AddField(
            model_name='taskcomments',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='TComment_task', to='academics.task'),
        ),
        migrations.AddField(
            model_name='taskcomments',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='TComment_user', to='accounts.employee'),
        ),
        migrations.AddField(
            model_name='taskcolumns',
            name='board',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='TColumn_board', to='academics.taskboards'),
        ),
        migrations.AddField(
            model_name='taskcolumns',
            name='branch_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_%(class)ss', to='organizations.branch'),
        ),
        migrations.AddField(
            model_name='taskcolumns',
            name='organization_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='organizations.organizations'),
        ),
        migrations.AddField(
            model_name='taskboards',
            name='branch_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_%(class)ss', to='organizations.branch'),
        ),
        migrations.AddField(
            model_name='taskboards',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Tboard_created', to='accounts.employee'),
        ),
        migrations.AddField(
            model_name='taskboards',
            name='organization_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='organizations.organizations'),
        ),
        migrations.AddField(
            model_name='taskactivitylogs',
            name='branch_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_%(class)ss', to='organizations.branch'),
        ),
        migrations.AddField(
            model_name='taskactivitylogs',
            name='organization_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='organizations.organizations'),
        ),
        migrations.AddField(
            model_name='taskactivitylogs',
            name='performed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='TActLog_performed', to='accounts.employee'),
        ),
        migrations.AddField(
            model_name='taskactivitylogs',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='TActLog_task', to='academics.task'),
        ),
        migrations.AddField(
            model_name='taskactivitylogs',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='TActLog_user', to='accounts.employee'),
        ),
        migrations.AddField(
            model_name='task',
            name='assigned_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Task_assigned', to='accounts.employee'),
        ),
        migrations.AddField(
            model_name='task',
            name='board',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Task_board', to='academics.taskboards'),
        ),
        migrations.AddField(
            model_name='task',
            name='branch_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_%(class)ss', to='organizations.branch'),
        ),
        migrations.AddField(
            model_name='task',
            name='column',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Task_column', to='academics.taskcolumns'),
        ),
        migrations.AddField(
            model_name='task',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Task_created', to='accounts.employee'),
        ),
        migrations.AddField(
            model_name='task',
            name='organization_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='organizations.organizations'),
        ),
        migrations.AddField(
            model_name='studenttarnsactions',
            name='accepted_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Strans_accepted', to='accounts.employee'),
        ),
        migrations.AddField(
            model_name='studenttarnsactions',
            name='branch_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_%(class)ss', to='organizations.branch'),
        ),
        migrations.AddField(
            model_name='studenttarnsactions',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Strans_group', to='academics.group'),
        ),
        migrations.AddField(
            model_name='studenttarnsactions',
            name='organization_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='organizations.organizations'),
        ),
        migrations.AddField(
            model_name='studenttarnsactions',
            name='related_transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='academics.studenttarnsactions'),
        ),
        migrations.AddField(
            model_name='studenttarnsactions',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Strans_student', to='academics.student'),
        ),
        migrations.AddField(
            model_name='studenttarnsactions',
            name='student_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Strans_Sgroup', to='academics.studentgroup'),
        ),
        migrations.AddField(
            model_name='studentpricing',
            name='branch_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_%(class)ss', to='organizations.branch'),
        ),
        migrations.AddField(
            model_name='studentpricing',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Spricing_course', to='academics.course'),
        ),
        migrations.AddField(
            model_name='studentpricing',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Sprice_created', to='accounts.employee'),
        ),
        migrations.AddField(
            model_name='studentpricing',
            name='organization_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='organizations.organizations'),
        ),
        migrations.AddField(
            model_name='studentpricing',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Spricing_student', to='academics.student'),
        ),
        migrations.AddField(
            model_name='studentgroupleaves',
            name='branch_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_%(class)ss', to='organizations.branch'),
        ),
        migrations.AddField(
            model_name='studentgroupleaves',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='SGLeave_created', to='accounts.employee'),
        ),
        migrations.AddField(
            model_name='studentgroupleaves',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='SGLeave_group', to='academics.group'),
        ),
        migrations.AddField(
            model_name='studentgroupleaves',
            name='leave_reason',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='SGLeave_Lreason', to='academics.leavereason'),
        ),
        migrations.AddField(
            model_name='studentgroupleaves',
            name='organization_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='organizations.organizations'),
        ),
        migrations.AddField(
            model_name='studentgroupleaves',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='SGLeave_student', to='academics.student'),
        ),
        migrations.AddField(
            model_name='studentgroupleaves',
            name='student_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='SGLeave_Sgroup', to='academics.studentgroup'),
        ),
        migrations.AddField(
            model_name='studentgroup',
            name='branch_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_%(class)ss', to='organizations.branch'),
        ),
        migrations.AddField(
            model_name='studentgroup',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Sgroup_group', to='academics.group'),
        ),
        migrations.AddField(
            model_name='studentgroup',
            name='organization_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='organizations.organizations'),
        ),
        migrations.AddField(
            model_name='studentgroup',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Sgroup_student', to='academics.student'),
        ),
        migrations.AddField(
            model_name='studentfreezes',
            name='branch_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_%(class)ss', to='organizations.branch'),
        ),
        migrations.AddField(
            model_name='studentfreezes',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='SFreeze_created', to='accounts.employee'),
        ),
        migrations.AddField(
            model_name='studentfreezes',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='SFreeze_group', to='academics.group'),
        ),
        migrations.AddField(
            model_name='studentfreezes',
            name='organization_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='organizations.organizations'),
        ),
        migrations.AddField(
            model_name='studentfreezes',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='SFreeze_student', to='academics.student'),
        ),
        migrations.AddField(
            model_name='studentbalances',
            name='branch_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_%(class)ss', to='organizations.branch'),
        ),
        migrations.AddField(
            model_name='studentbalances',
            name='organization_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='organizations.organizations'),
        ),
        migrations.AddField(
            model_name='studentbalances',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Sbalances_student', to='academics.student'),
        ),
        migrations.AddField(
            model_name='studentbalancehistory',
            name='branch_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_%(class)ss', to='organizations.branch'),
        ),
        migrations.AddField(
            model_name='studentbalancehistory',
            name='organization_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='organizations.organizations'),
        ),
        migrations.AddField(
            model_name='studentbalancehistory',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='SBHistory_student', to='academics.student'),
        ),
        migrations.AddField(
            model_name='student',
            name='branch_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_%(class)ss', to='organizations.branch'),
        ),
        migrations.AddField(
            model_name='student',
            name='organization_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='organizations.organizations'),
        ),
        migrations.AddField(
            model_name='room',
            name='branch_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_%(class)ss', to='organizations.branch'),
        ),
        migrations.AddField(
            model_name='room',
            name='organization_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='organizations.organizations'),
        ),
        migrations.AddField(
            model_name='lessontime',
            name='branch_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_%(class)ss', to='organizations.branch'),
        ),
        migrations.AddField(
            model_name='lessontime',
            name='organization_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='organizations.organizations'),
        ),
        migrations.AddField(
            model_name='lessonschedule',
            name='branch_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_%(class)ss', to='organizations.branch'),
        ),
        migrations.AddField(
            model_name='lessonschedule',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_group', to='academics.group'),
        ),
        migrations.AddField(
            model_name='lessonschedule',
            name='organization_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='organizations.organizations'),
        ),
        migrations.AddField(
            model_name='leavereason',
            name='branch_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_%(class)ss', to='organizations.branch'),
        ),
        migrations.AddField(
            model_name='leavereason',
            name='organization_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='organizations.organizations'),
        ),
        migrations.AddField(
            model_name='groupteacher',
            name='branch_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_%(class)ss', to='organizations.branch'),
        ),
        migrations.AddField(
            model_name='groupteacher',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group', to='academics.group'),
        ),
        migrations.AddField(
            model_name='groupteacher',
            name='organization_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='organizations.organizations'),
        ),
        migrations.AddField(
            model_name='groupteacher',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher', to='accounts.employee'),
        ),
        migrations.AddField(
            model_name='group',
            name='branch_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_%(class)ss', to='organizations.branch'),
        ),
        migrations.AddField(
            model_name='group',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group_course', to='academics.course'),
        ),
        migrations.AddField(
            model_name='group',
            name='organization_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='organizations.organizations'),
        ),
        migrations.AddField(
            model_name='group',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group_room', to='academics.room'),
        ),
        migrations.AddField(
            model_name='exams',
            name='branch_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_%(class)ss', to='organizations.branch'),
        ),
        migrations.AddField(
            model_name='exams',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exam_created', to='accounts.employee'),
        ),
        migrations.AddField(
            model_name='exams',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams_group', to='academics.group'),
        ),
        migrations.AddField(
            model_name='exams',
            name='organization_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='organizations.organizations'),
        ),
        migrations.AddField(
            model_name='examresults',
            name='branch_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_%(class)ss', to='organizations.branch'),
        ),
        migrations.AddField(
            model_name='examresults',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exam_res_created', to='accounts.employee'),
        ),
        migrations.AddField(
            model_name='examresults',
            name='exam',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exam', to='academics.exams'),
        ),
        migrations.AddField(
            model_name='examresults',
            name='organization_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='organizations.organizations'),
        ),
        migrations.AddField(
            model_name='examresults',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exam_res_student', to='academics.student'),
        ),
        migrations.AddField(
            model_name='course',
            name='branch_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_%(class)ss', to='organizations.branch'),
        ),
        migrations.AddField(
            model_name='course',
            name='lesson',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Course_lesson', to='academics.lessontime'),
        ),
        migrations.AddField(
            model_name='course',
            name='organization_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='organizations.organizations'),
        ),
        migrations.AddField(
            model_name='attendence',
            name='branch_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_%(class)ss', to='organizations.branch'),
        ),
        migrations.AddField(
            model_name='attendence',
            name='marked_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='A_marked', to='accounts.employee'),
        ),
        migrations.AddField(
            model_name='attendence',
            name='organization_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='organizations.organizations'),
        ),
        migrations.AddField(
            model_name='attendence',
            name='student_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='A_Sgroup', to='academics.studentgroup'),
        ),
    ]
